# Generated by Django 6.0.6 on 2026-06-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0003_alter_backgroundjob_job_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("tasks", "Tasks"),
                            ("archive", "Archive"),
                            ("weekly_summary", "Weekly summary"),
                            ("tag_summary", "Tag summary"),
                            ("notification_report", "Notification report"),
                            ("jobs_report", "Jobs report"),
                            ("imports_report", "Imports report"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "XLSX")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("file_path", models.TextField(blank=True, default="")),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("rows_count", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "background_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_exports",
                        to="jobs.backgroundjob",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="idx_analytics_export_status",
                    ),
                    models.Index(
                        condition=models.Q(("expires_at__isnull", False)),
                        fields=["expires_at"],
                        name="idx_analytics_export_expires",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rows_count__isnull", True),
                            ("rows_count__gte", 0),
                            _connector="OR",
                        ),
                        name="chk_analytics_export_rows",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("file_size_bytes__isnull", True),
                            ("file_size_bytes__gte", 0),
                            _connector="OR",
                        ),
                        name="chk_analytics_export_size",
                    ),
                ],
            },
        ),
    ]
