# Generated by Django 6.0.6 on 2026-06-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsexportjob",
            name="file_format",
            field=models.CharField(
                choices=[("csv", "CSV"), ("xlsx", "XLSX"), ("pdf", "PDF")],
                max_length=20,
            ),
        ),
    ]
