# Generated by Django 6.0.6 on 2026-06-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="uq_boards_single_default",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BoardColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("review", "Review"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="slate", max_length=20)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("wip_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="boards.board",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 0)),
                        name="chk_board_columns_position_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("wip_limit__isnull", True),
                            ("wip_limit__gt", 0),
                            _connector="OR",
                        ),
                        name="chk_board_columns_wip_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("board", "position"),
                        name="uq_board_columns_board_position_active",
                    ),
                ],
            },
        ),
    ]
