# Generated by Django 6.0.6 on 2026-06-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_seed_default_board"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="boardcolumn",
            index=models.Index(
                fields=["board", "is_active", "position"],
                name="idx_board_columns_board_active_position",
            ),
        ),
        migrations.AddIndex(
            model_name="boardcolumn",
            index=models.Index(
                fields=["system_type"], name="idx_board_columns_system_type"
            ),
        ),
    ]
