# Generated by Django 6.0.6 on 2026-06-23 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0005_localize_default_board"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="boardcolumn",
            options={"ordering": ("position",)},
        ),
    ]
