# Generated by Django 6.0.6 on 2026-06-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0006_alter_model_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_transitions",
                        to="boards.board",
                    ),
                ),
                (
                    "from_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="boards.boardcolumn",
                    ),
                ),
                (
                    "to_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="boards.boardcolumn",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["board", "from_column"], name="idx_col_trans_board_from"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_column", "to_column"),
                        name="uq_column_transition_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_column", models.F("to_column")), _negated=True
                        ),
                        name="chk_column_transition_distinct",
                    ),
                ],
            },
        ),
    ]
