# Generated by Django 6.0.6 on 2026-06-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0007_column_transition"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="boardcolumn",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="boardcolumn",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("blocked", "Blocked"),
                    ("review", "Review"),
                    ("ready", "Ready"),
                    ("done", "Done"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="active_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boards",
                to="boards.boardscheme",
            ),
        ),
        migrations.CreateModel(
            name="BoardSchemeColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("review", "Review"),
                            ("ready", "Ready"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="slate", max_length=20)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="boards.boardscheme",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scheme", "position"),
                        name="uq_board_scheme_column_position",
                    ),
                    models.UniqueConstraint(
                        fields=("scheme", "system_type"),
                        name="uq_board_scheme_column_system_type",
                    ),
                ],
            },
        ),
    ]
