# Generated by Django 6.0.6 on 2026-06-23 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0009_reset_to_default_scheme"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boardschemecolumn",
            name="uq_board_scheme_column_system_type",
        ),
    ]
