# Generated by Django 6.0.6 on 2026-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0021_board_scheme_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="on_flow",
            field=models.BooleanField(default=False),
        ),
    ]
