# Generated by Django 6.0.6 on 2026-06-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0002_alter_backgroundjob_job_type"),
        ("tasks", "0003_alter_task_options_alter_taskevent_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramCallbackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_user_id", models.CharField(max_length=80)),
                ("chat_id", models.CharField(max_length=80)),
                ("callback_query_id", models.CharField(max_length=120, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("task_done", "Task done"),
                            ("task_in_progress", "Task in progress"),
                            ("task_snooze", "Task snooze"),
                            ("task_cancel_reminders", "Cancel reminders"),
                        ],
                        max_length=60,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_callbacks",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_chat_id", models.CharField(max_length=80)),
                ("message_text", models.TextField()),
                ("message_id", models.CharField(blank=True, default="", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("overdue", "Overdue"),
                            ("stale_in_progress", "Stale in progress"),
                            ("stale_planned", "Stale planned"),
                            ("reminder", "Reminder"),
                            ("manual", "Manual"),
                        ],
                        max_length=60,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("dedup_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "background_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_jobs",
                        to="jobs.backgroundjob",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_jobs",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="idx_notif_status_scheduled",
                    ),
                    models.Index(
                        fields=["task", "-created_at"], name="idx_notif_task_created"
                    ),
                ],
            },
        ),
    ]
