# Generated by Django 6.0.6 on 2026-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramcallbacklog",
            name="action",
            field=models.CharField(
                choices=[
                    ("task_done", "Task done"),
                    ("task_in_progress", "Task in progress"),
                    ("task_set_status", "Set task status"),
                    ("task_snooze", "Task snooze"),
                    ("task_cancel_reminders", "Cancel reminders"),
                ],
                max_length=60,
            ),
        ),
    ]
