# Generated by Django 6.0.6 on 2026-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_seed_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="stale_in_progress_minutes",
            field=models.PositiveIntegerField(default=4320),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="stale_planned_minutes",
            field=models.PositiveIntegerField(default=10080),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="telegram_default_chat_id",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
