# Generated by Django 6.0.6 on 2026-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_projectsettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="week_rollover_iso_week",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsettings",
            name="week_rollover_iso_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
