# Generated by Django 6.0.6 on 2026-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("json_inbox_scan", "JSON inbox scan"),
                            ("json_import_file", "JSON import file"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="idx_jobs_status_scheduled",
                    ),
                    models.Index(
                        fields=["job_type", "-created_at"], name="idx_jobs_type_created"
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="idx_jobs_celery_task_id"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("attempts__gte", 0)),
                        name="chk_background_jobs_attempts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_attempts__gt", 0)),
                        name="chk_background_jobs_max_attempts",
                    ),
                ],
            },
        ),
    ]
