# Generated by Django 6.0.6 on 2026-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("json_inbox_scan", "JSON inbox scan"),
                    ("json_import_file", "JSON import file"),
                    ("notification_scan", "Notification scan"),
                    ("telegram_send", "Telegram send"),
                    ("telegram_callback", "Telegram callback"),
                ],
                max_length=80,
            ),
        ),
    ]
