# Generated by Django 6.0.6 on 2026-06-21 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("boards", "0002_seed_default_board"),
        ("core", "0002_seed_tags"),
        ("weeks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("column_entered_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ui", "UI"),
                            ("api", "API"),
                            ("json_import", "JSON import"),
                            ("telegram", "Telegram"),
                            ("system", "System"),
                        ],
                        default="ui",
                        max_length=40,
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("evidence_url", models.TextField(blank=True, default="")),
                ("completion_note", models.TextField(blank=True, default="")),
                ("reminder_enabled", models.BooleanField(default=True)),
                ("next_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reminder_interval_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tasks",
                        to="boards.board",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tasks",
                        to="boards.boardcolumn",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="weeks.week",
                    ),
                ),
            ],
            options={
                "ordering": ["column_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="TaskTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tag"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                related_name="tasks", through="tasks.TaskTag", to="core.tag"
            ),
        ),
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("moved", "Moved"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                            ("reopened", "Reopened"),
                            ("reminder_scheduled", "Reminder scheduled"),
                            ("notification_sent", "Notification sent"),
                            ("telegram_action", "Telegram action"),
                            ("imported", "Imported"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("api", "API"),
                            ("import", "Import"),
                            ("telegram", "Telegram"),
                            ("system", "System"),
                        ],
                        max_length=40,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, default="", max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ui", "UI"),
                            ("api", "API"),
                            ("json_import", "JSON import"),
                            ("telegram", "Telegram"),
                            ("system", "System"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "-created_at"],
                        name="idx_task_events_task_created",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="idx_task_events_type_created",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tasktag",
            index=models.Index(fields=["tag", "task"], name="idx_task_tags_tag_task"),
        ),
        migrations.AddConstraint(
            model_name="tasktag",
            constraint=models.UniqueConstraint(
                fields=("task", "tag"), name="uq_task_tags_task_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("archived_at__isnull", True)),
                fields=["board", "column", "position"],
                name="idx_tasks_board_column_position_active",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["week", "archived_at", "column", "position"],
                name="idx_tasks_week_active",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("archived_at__isnull", False)),
                fields=["archived_at", "-closed_at"],
                name="idx_tasks_archived_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(
                    ("archived_at__isnull", True), ("due_at__isnull", False)
                ),
                fields=["due_at"],
                name="idx_tasks_due_active",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    ("next_reminder_at__isnull", False),
                    ("reminder_enabled", True),
                ),
                fields=["next_reminder_at"],
                name="idx_tasks_next_reminder",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["source", "created_at"], name="idx_tasks_source_created"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("archived_at__isnull", True)),
                fields=["column", "column_entered_at"],
                name="idx_tasks_column_entered_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="chk_tasks_title_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 0)),
                name="chk_tasks_position_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reminder_interval_minutes__isnull", True),
                    ("reminder_interval_minutes__gt", 0),
                    _connector="OR",
                ),
                name="chk_tasks_reminder_interval_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("archived_at__isnull", True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="chk_tasks_archive_after_close",
            ),
        ),
    ]
