# Generated by Django 6.0.6 on 2026-06-22 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_task_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("column_id", "position")},
        ),
        migrations.AlterModelOptions(
            name="taskevent",
            options={"ordering": ("-created_at",)},
        ),
    ]
