# Generated by Django 6.0.6 on 2026-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
