# Generated by Django 6.0.6 on 2026-06-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_task_story_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("epic", "Epic"),
                    ("story", "Story"),
                    ("task", "Task"),
                    ("bug", "Bug"),
                ],
                default="task",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TaskLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("relates", "Related"),
                            ("blocks", "Blocks"),
                            ("duplicates", "Duplicates"),
                        ],
                        default="relates",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="tasks.task",
                    ),
                ),
                (
                    "to_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_task", "link_type"], name="idx_task_links_from"
                    ),
                    models.Index(
                        fields=["to_task", "link_type"], name="idx_task_links_to"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_task", "to_task", "link_type"),
                        name="uq_task_links_from_to_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_task", models.F("to_task")), _negated=True
                        ),
                        name="chk_task_links_not_self",
                    ),
                ],
            },
        ),
    ]
