# Generated by Django 6.0.6 on 2026-06-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_year", models.PositiveIntegerField()),
                ("iso_week", models.PositiveIntegerField()),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("review_notes", models.TextField(blank=True, default="")),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-iso_year", "-iso_week"],
                "indexes": [
                    models.Index(fields=["closed_at"], name="idx_weeks_closed_at")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("iso_year", "iso_week"), name="uq_weeks_iso_year_week"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("iso_week__gte", 1), ("iso_week__lte", 53)),
                        name="chk_weeks_iso_week",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("starts_on__lte", models.F("ends_on"))),
                        name="chk_weeks_range",
                    ),
                ],
            },
        ),
    ]
