# Generated by Django 6.0.6 on 2026-06-23 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weeks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="week",
            options={"ordering": ("-iso_year", "-iso_week")},
        ),
    ]
