# Generated by Django 6.0.6 on 2026-06-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("original_path", models.TextField()),
                ("checksum", models.CharField(max_length=128)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("schema_version", models.CharField(default="", max_length=20)),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped_duplicate", "Skipped duplicate"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("tasks_created", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="idx_import_logs_status_created",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("tasks_created__gte", 0)),
                        name="chk_import_logs_tasks_created",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("idempotency_key",),
                        name="uq_import_logs_idempotency_key",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["succeeded", "skipped_duplicate"])
                        ),
                        fields=("checksum",),
                        name="uq_import_logs_success_checksum",
                    ),
                ],
            },
        ),
    ]
